version: '3.8'

services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=TaskPass123!
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql

  api:
    build:
      context: ./Backend/TaskTrackerAPI
      dockerfile: Dockerfile
    ports:
      - "32769:8080"
      - "32770:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=TaskTrackerDb;User Id=sa;Password=TaskPass123!;TrustServerCertificate=True
    depends_on:
      - sql-server

volumes:
  sqldata:
